# Generated by Django 4.2.2 on 2025-11-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_phone'),
        ('account', '0006_remove_profile_names_emails'),
    ]

    operations = [
    ]
