# Generated by Django 4.2.2 on 2025-11-03 13:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20251103_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENT', 'เปอร์เซ็นต์'), ('FIXED', 'จำนวนเงินคงที่')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('percent_max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='จำกัดส่วนลดสูงสุดเมื่อเป็นเปอร์เซ็นต์ (ไม่บังคับ)', max_digits=10, null=True)),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('allowed_levels', models.JSONField(default=list, help_text='ตัวอย่าง: ["SILVER", "GOLD"]')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='ทั้งหมดกี่ครั้ง (เว้นว่าง=ไม่จำกัด)', null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('max_uses_per_user', models.PositiveIntegerField(blank=True, help_text='ต่อผู้ใช้กี่ครั้ง (เว้นว่าง=ไม่จำกัด)', null=True)),
                ('stackable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=64)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='account.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['code'], name='account_cou_code_2e3dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['active', 'starts_at', 'ends_at'], name='account_cou_active_1c6376_idx'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['user', 'coupon'], name='account_cou_user_id_f6a7ac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='couponredemption',
            unique_together={('coupon', 'user', 'order_id')},
        ),
    ]
