# Generated by Django 4.2.2 on 2025-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_coupon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='required_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
