# Generated by Django 5.2.7 on 2025-11-04 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_coupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='image_code',
            field=models.ImageField(blank=True, null=True, upload_to='coupons_qr/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
