# Generated by Django 5.2.7 on 2025-11-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_coupon_image_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
