# Generated by Django 5.2.7 on 2025-11-09 14:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_pointtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_text', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='promotions/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='เลขมากอยู่บน (สำหรับจัดลำดับแสดงผล)')),
                ('min_spend', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('allowed_levels', models.JSONField(blank=True, default=list, help_text='ตัวอย่าง: ["SILVER","GOLD","PREMIUM"]; เว้นว่าง = ทุกเลเวล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='account.coupon')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/gallery/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='account.promotion')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PromotionTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'view'), ('click', 'click')], max_length=10)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='account.promotion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['active', 'starts_at', 'ends_at'], name='account_pro_active_84e496_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['priority', 'active'], name='account_pro_priorit_9a15ce_idx'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['slug'], name='account_pro_slug_dfda5e_idx'),
        ),
        migrations.AddIndex(
            model_name='promotiontracking',
            index=models.Index(fields=['promotion', 'action', 'at'], name='account_pro_promoti_24964f_idx'),
        ),
    ]
