# Generated by Django 5.2.7 on 2025-11-14 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_brand_coupon_brand_couponitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # ลบ indexes ก่อนที่จะลบฟิลด์
        migrations.RemoveIndex(
            model_name='couponitem',
            name='account_cou_coupon__7d0eba_idx',
        ),
        migrations.RemoveIndex(
            model_name='couponitem',
            name='account_cou_expires_2fd57c_idx',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='couponitem',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='couponitem',
            name='used_by',
        ),
        migrations.RemoveField(
            model_name='couponredemption',
            name='coupon_item',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='CouponItem',
        ),
    ]
