# Generated by Django 5.2.7 on 2025-11-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_partner_remove_coupon_brand_remove_couponitem_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='category',
            field=models.CharField(choices=[('partner', 'คูปองพาร์ทเนอร์'), ('ddream', 'คูปองดีดรีม')], default='partner', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('all', 'ทั้งหมด'), ('special', 'พิเศษสำหรับคุณ'), ('used', 'ใช้แล้ว/หมดอายุ')], default='all', max_length=20),
        ),
    ]
