# Generated by Django 5.2.7 on 2025-11-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_partner_category_partner_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='available_branches',
            field=models.TextField(blank=True, help_text='สาขาที่ใช้งานได้'),
        ),
    ]
