# Generated by Django 5.2.7 on 2025-11-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_coupon_available_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='available_branches',
            field=models.TextField(blank=True, help_text='สาขาที่ใช้งานได้'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(blank=True, help_text='ข้อมูลเพิ่มเติมเกี่ยวกับพาร์ทเนอร์', max_length=255),
        ),
    ]
