# Generated by Django 5.2.7 on 2025-11-14 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_partner_available_branches_partner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='พาร์ทเนอร์ที่เป็นเจ้าของคูปองนี้', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='account.partner'),
        ),
    ]
