# Generated by Django 5.2.7 on 2025-11-17 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_coupon_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponSlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='ชื่อรูปภาพ', max_length=255)),
                ('image', models.ImageField(help_text='รูปภาพคูปอง', upload_to='coupon_slides/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('is_active', models.BooleanField(default=True, help_text='สถานะการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รูปภาพคูปอง',
                'verbose_name_plural': 'รูปภาพคูปอง',
                'ordering': ['-created_at'],
            },
        ),
    ]
