# Generated by Django 5.2.7 on 2025-11-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_couponslideimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couponslideimage',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'รูปภาพคูปอง', 'verbose_name_plural': 'รูปภาพคูปอง'},
        ),
        migrations.AddField(
            model_name='couponslideimage',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='ลำดับการแสดงผล (น้อยไปมาก)'),
        ),
    ]
