# Generated by Django 5.2.7 on 2025-11-18 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_couponslideimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponslideimage',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='เชื่อมโยงกับพาร์ทเนอร์ (คลิกรูปจะแสดงคูปอง)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_images', to='account.partner'),
        ),
    ]
